create table search_request_query
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT,
    ip_address TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    query TEXT,
    category TEXT,
    search_request TEXT
);