create table renter
(
    id bigint primary key generated by default as identity,
    first_name text null,
    last_name text null,
    phone_number text null,
    email text null,
    location bigint references location (id) null,
    created_at timestamp null,
    entered_by_user text references usr(id) null,
    transaction_id bigint references transaction (id) null
);

alter table usr add column renter_information bigint references renter (id) null;

alter table transaction add column renter_information bigint references renter (id) null;

insert into renter (first_name, email, created_at, entered_by_user, transaction_id)
select u.username, u.email, ts.created_timestamp, u.id, t.id from transaction t
    join usr u on t.renter_id = u.id
    join transaction_status ts on t.current_status_id = ts.id;

update transaction t set renter_information = r.id from renter r where t.id = r.transaction_id;

alter table transaction drop column renter_id;
alter table renter drop column transaction_id;
alter table transaction alter column renter_information set not null;