CREATE TYPE transaction_status_enum AS ENUM ('INITIALIZED', 'PAID', 'ACCEPTED', 'COMPLETED', 'PAID_OUT', 'CANCELLED');

create table transaction_status(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    createdTimestamp timestamp not null,
    notes text,
    status transaction_status_enum not null default 'INITIALIZED'
);

create table transaction
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rental_item_id BIGINT not null,
    renter text not null,
    start_date date not null,
    end_date date not null,
    price numeric not null,
    current_status_id bigint not null,
    foreign key (current_status_id) references transaction_status (id),
    FOREIGN KEY (rental_item_id) REFERENCES rental_item (id),
    FOREIGN KEY (renter) REFERENCES usr (id)
);

alter table transaction_status
    add transaction_id bigint not null default 0,
    add foreign key (transaction_id) references transaction (id)
