version: '3'
services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sharerental-be
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sharerental
    networks:
      - postgres-network

networks:
  postgres-network: