server:
  servlet:
    context-path: /backend
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: sharerental-be
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/sharerental?stringtype=unspecified
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/sharerental-b66f7
  cloud:
    gcp:
      project-id: sharerental-b66f7

logging:
  level:
    nl:
      sharerental:
        be: DEBUG

gcp:
  bucket:
    public:
      name: sharerental-staging

mollie:
  apiKey: test_5nGU9dSj578p2RtgKSkrGPsDp2g9uV

shareRental:
  callbackUrl: http://localhost:3000/transaction/completed
  webhookUrl:  https://36c1-185-132-108-115.ngrok-free.app/backend/transaction/mollie-callback