server:
  servlet:
    context-path: /backend
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: sharerental-be
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/sharerental?stringtype=unspecified
    tomcat:
#      max connections for postgresql is 25, where the last 5 are reserved for admin connections.
#      Set this to 15 so manual connections can be made to the database.
      max-active: 15
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/sharerental-b66f7
  cloud:
    gcp:
      project-id: sharerental-b66f7

logging:
  level:
    nl:
      sharerental:
        be: DEBUG
gcp:
  bucket:
    public:
      name: sharerental-staging

mollie:
  apiKey: test_5nGU9dSj578p2RtgKSkrGPsDp2g9uV

one-signal:
  mock: true
  app-id: 138e9f48-cac7-4963-9f20-47b8399e187a
  api-key: bungus
  templates:
    welcome-email: 81429d3e-cde7-45b4-8385-790ee1ab9875
    item-rented: 1591f7aa-7148-4f26-89ef-3f5f08b3c22c

share-rental:
  callback-url: http://localhost:3000/transaction/completed
  webhook-url: https://2722-185-132-108-115.ngrok-free.app/backend/transaction/mollie-callback

ngrok:
  enabled: true
  auth-token: 2VtukgpNnE6MmsmLeAIyoSmX1iv_2dRWq8zfkE9YsVhzsTzqS