spring:
  datasource:
    username: sharerental-be
    url: jdbc:postgresql://10.13.144.3:5432/sharerental?stringtype=unspecified


gcp:
  bucket:
    public:
      name: sharerental

share-rental:
  callback-url: https://sharerental.nl/transaction/completed
  webhook-url: https://sharerental.nl/backend/transactions/mollie-callback

  slack:
    platform-events-url:

one-signal:
  mock: false
ngrok:
  enabled: false