spring:
  datasource:
    username: sharerental-be
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.13.144.3:5432/sharerental?stringtype=unspecified


gcp:
  bucket:
    public:
      name: sharerental

shareRental:
  callbackUrl: https://sharerental.nl/transaction/completed
  webhookUrl: https://sharerental.nl/backend/transaction/mollie-callback

ngrok:
  enabled: false