openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /user:
    get:
      tags:
        - user
      summary: Get the user context
      responses:
        200:
          description: Successful user context retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        fullName:
          type: string
          example: "Luc Klaassen"
        name:
          type: string
          example: "Luc"

