openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /registered:
    post:
      summary: Register a new user
      operationId: registerUser
      tags:
          - user
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      responses:
        201:
          description: successful operation
  /contact-form:
    post:
      summary: Send a contact form
      operationId: sendContactForm
      tags:
        - contact-form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactForm'
      responses:
        201:
          description: Item created successfully
  /zipcode:
    get:
      summary: Get address information based on a zipcode
      operationId: getAddressByZipcode
      tags:
        - zipcode
      parameters:
        - name: zipcode
          in: query
          required: true
          schema:
            type: string
          example: "1234AB"
        - name: houseNumber
          in: query
          required: true
          schema:
            type: string
          example: "1"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  street:
                    type: string
                    example: "Kerkstraat"
                  city:
                    type: string
                    example: "Amsterdam"
                  province:
                    type: string
                    example: "Noord-Holland"
                  country:
                    type: string
                    example: "Nederland"
                  additions:
                    type: array
                    items:
                      type: string
                      example: ["A", "B"]
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
          - email
          - userType
      properties:
        name:
          type: string
          example: "frans@bouwmans.nl"
        userType:
          type: string
          format: enum
          enum:
              - RENTER
              - LESSOR
    ContactForm:
      type: object
      required:
          - name
          - email
          - phone
      properties:
        name:
          type: string
          example: "Frans"
        email:
          type: string
          example: "luc.klaassen@sharerental.app"
        phone:
          type: string
          example: "+31 6 43209314"
        analyticsToken:
          type: string
          example: "UA-123456789-1"