openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /contact-form:
    post:
      summary: Send a contact form
      operationId: sendContactForm
      tags:
        - contact-form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactForm'
      responses:
        201:
          description: Item created successfully
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ContactForm:
      type: object
      required:
          - name
          - email
          - phone
      properties:
        name:
          type: string
          example: "Frans"
        email:
          type: string
          example: "luc.klaassen@sharerental.app"
        phone:
          type: string
          example: "+31 6 43209314"
        analyticsToken:
          type: string
          example: "UA-123456789-1"