---
servers:
- url: "http://localhost:8080"
openapi: "3.0.3"
paths:
  /me/rental-items:
    $ref: "./rentalItem.yaml#/paths/~1rental-items"
  /me/rental-items/{id}:
    $ref: "./rentalItem.yaml#/paths/~1rental-items~1{id}"
  /me/rental-items/{id}/images:
    $ref: "./rentalItem.yaml#/paths/~1rental-items~1{id}~1images"
  /me/rental-items/{id}/images/{imageId}:
    $ref: "./rentalItem.yaml#/paths/~1rental-items~1{id}~1images~1{imageId}"
  /search:
    $ref: "./search.yaml#/paths/~1search"
  /details/{slug}:
    $ref: "./search.yaml#/paths/~1details~1{slug}"
  /me/lessor/{id}:
    $ref: "./lessor.yaml#/paths/~1lessors~1{id}"
  /me/lessor:
    $ref: "./lessor.yaml#/paths/~1lessors"
  /transaction/calculate-price:
    $ref: "./transaction.yaml#/paths/~1transactions~1calculate-price"
  /transaction/get-amount-available-for-date:
    $ref: "./transaction.yaml#/paths/~1transactions~1get-amount-available-for-date"
  /transaction:
    $ref: "./transaction.yaml#/paths/~1transactions"
  /me/transactions:
    $ref: "./transaction.yaml#/paths/~1transactions"
  /transaction/mollie-callback:
    $ref: "./transaction.yaml#/paths/~1transactions~1mollie-callback"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
