openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /renter:
    get:
      summary: Get renter
      tags:
          - renter
      operationId: getRenter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Renter'
    post:
      summary: Create renter
      tags:
          - renter
      operationId: createRenter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenterInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Renter'
components:
  schemas:
    Renter:
      type: object
      required:
        - id
        - firstName
        - lastName
        - phoneNumber
        - email
        - location
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        location:
          $ref: './utils/Location.yaml#/components/schemas/Location'
    RenterInput:
      type: object
      required:
        - firstName
        - lastName
        - phoneNumber
        - email
      properties:
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
