openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /me/rentalItem:
    get:
      tags:
        - rentalItem
      operationId: getRentalItems
      summary: Find all items for user
      security:
        - BearerAuth: [ ]
      parameters:
        - in: query
          name: Pageable
          schema:
            $ref: './utils/PaginationParameters.yaml/#/Pageable'
      responses:
        200:
          description: Successful result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRentalItemsResult'
    post:
      summary: Create a new rental item
      operationId: createRentalItem
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RentalItem'
      responses:
        201:
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentalItem'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    GetRentalItemsResult:
      type: object
      required:
        - _embedded
        - page
      properties:
        _embedded:
          type: array
          items:
            $ref: '#/components/schemas/RentalItem'
        page:
          $ref: './utils/PaginationResponse.yaml'
    Image:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
      required:
        - id
        - url
    ImageInput:
      type: object
      properties:
        url:
          type: string
      required:
        - url
    FuelType:
      type: string
      enum: [ GASOLINE, DIESEL, ELECTRIC, OTHER ]
    RentalItemInput:
      type: object
      properties:
        name:
          type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageInput'
        number:
          type: string
        shortDescription:
          type: string
        longDescription:
          type: string
        price_24h:
          type: number
          format: double
        price_48h:
          type: number
          format: double
        price_168h:
          type: number
          format: double
        deliveryPossible:
          type: boolean
        deliveryPrice:
          type: number
          format: double
        category:
          type: string
        reachMeters:
          type: number
          format: double
        carryingWeightKilograms:
          type: number
          format: double
        maximumWorkHeightMeters:
          type: number
          format: double
        intrinsicWeightKilograms:
          type: number
          format: double
        materialType:
          type: string
        brand:
          type: string
        maximumPressureBars:
          type: number
          format: double
        maximumHorsePower:
          type: number
          format: double
        requiredPowerVoltageVolt:
          type: number
          format: double
        workWidthMeters:
          type: number
          format: double
        vacuumAttachmentPossible:
          type: boolean
        capacityLiters:
          type: number
          format: double
        itemHeight:
          type: number
          format: double
        itemWidth:
          type: number
          format: double
        itemLength:
          type: number
          format: double
        powerWatt:
          type: number
          format: double
        maximumSurfaceSquareMeters:
          type: number
          format: double
        fuelType:
          $ref: '#/components/schemas/FuelType'
      required:
        - name
    RentalItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        number:
          type: string
        shortDescription:
          type: string
        longDescription:
          type: string
        price_24h:
          type: number
          format: double
        price_48h:
          type: number
          format: double
        price_168h:
          type: number
          format: double
        deliveryPossible:
          type: boolean
        deliveryPrice:
          type: number
          format: double
        category:
          type: string
        reachMeters:
          type: number
          format: double
        carryingWeightKilograms:
          type: number
          format: double
        maximumWorkHeightMeters:
          type: number
          format: double
        intrinsicWeightKilograms:
          type: number
          format: double
        materialType:
          type: string
        brand:
          type: string
        maximumPressureBars:
          type: number
          format: double
        maximumHorsePower:
          type: number
          format: double
        requiredPowerVoltageVolt:
          type: number
          format: double
        workWidthMeters:
          type: number
          format: double
        vacuumAttachmentPossible:
          type: boolean
        capacityLiters:
          type: number
          format: double
        itemHeight:
          type: number
          format: double
        itemWidth:
          type: number
          format: double
        itemLength:
          type: number
          format: double
        powerWatt:
          type: number
          format: double
        maximumSurfaceSquareMeters:
          type: number
          format: double
        fuelType:
          $ref: '#/components/schemas/FuelType'
      required:
        - id
        - name
