openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /renter:
    get:
      summary: Get renter
      tags:
          - renter
      operationId: getRenter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Renter'
components:
  schemas:
    Renter:
      type: object
      required:
        - id
        - RenterType
        - firstName
        - lastName
        - phoneNumber
        - email
        - location
      properties:
        id:
          type: integer
          format: int64
        RenterType:
          $ref: './utils/RenterType.yaml#/components/schemas/RenterType'
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        location:
          $ref: './utils/Location.yaml#/components/schemas/Location'
        chamberOfCommerce:
          type: string
        vatNumber:
          type: string
        companyName:
          type: string
