openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /me/renter:
    get:
      tags:
        - renter
      operationId: getRenter
      summary: Find all renters for user
      security:
        - BearerAuth: [ ]
      parameters:
        - in: query
          name: Pageable
          schema:
            $ref: './utils/PaginationParameters.yaml/#/Pageable'
      responses:
        200:
          description: Successful result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRenterResult'
    post:
      summary: Create a new renter
      operationId: createRenter
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenterInput'
      responses:
        201:
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Renter'
  /me/renter/{id}:
    put:
      summary: Update a renter
      operationId: updateRenter
      security:
        - BearerAuth: [ ]
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenterInput'
      responses:
        201:
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Renter'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    GetRenterResult:
      type: object
      required:
        - _embedded
        - page
      properties:
        _embedded:
          type: array
          items:
            $ref: '#/components/schemas/Renter'
        page:
          $ref: './utils/PaginationResponse.yaml'
    Renter:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Franskes machineverhuur"
        description:
          type: string
          example: "Machineverhuur voor iedereen!"
        primaryLocation:
          $ref: '#/components/schemas/Location'
        locations:
          type: array
          items:
            $ref: '#/components/schemas/Location'
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        houseNumberAddition:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
    RenterInput:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          example: "Franskes machineverhuur"
        description:
          type: string
          example: "Machineverhuur voor iedereen!"
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        houseNumberAddition:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
