openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /rental-items/{id}:
    get:
      tags:
        - rentalItem
      operationId: getRentalItem
      summary: Find a specific item
      security:
        - BearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful result
          content:
            application/json:
              schema:
                $ref: './utils/RentalItem.yaml#/components/schemas/RentalItem'
    post:
      tags:
        - rentalItem
      operationId: updateRentalItem
      summary: Update a specific item
      security:
        - BearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './utils/RentalItem.yaml#/components/schemas/RentalItemInput'
      responses:
        200:
          description: Successful result
          content:
            application/json:
              schema:
                $ref: './utils/RentalItem.yaml#/components/schemas/RentalItem'
  /rental-items/{id}/images/{imageId}:
    delete:
      tags:
        - rentalItemImage
      operationId: deleteRentalItemImage
      summary: Delete an image
      security:
        - BearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: imageId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successfully deleted
  /rental-items/{id}/images:
    get:
      tags:
        - rentalItemImage
      operationId: getRentalItemImages
      summary: Find images of a specific item
      security:
        - BearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentalItemImagesResult'
    post:
      tags:
        - rentalItemImage
      operationId: uploadRentalItemImage
      summary: Upload an image
      security:
        - BearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files[]:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        200:
          description: Successful result
  /rental-items:
    get:
      tags:
        - rentalItem
      operationId: getRentalItems
      summary: Find all items for user
      security:
        - BearerAuth: [ ]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            format: int32
            default: 0
            example: '5'
          required: false
          description: Pagenumber, default value is 0 (first page).
        - in: query
          name: size
          schema:
            type: integer
            format: int32
            default: 8
            example: '25'
          description: The page size, number of items to return. Default value is 8.
          required: false
        - in: query
          name: sort
          schema:
            type: array
            items:
              type: string
              maxLength: 50
            example: 'price;desc,name;asc'
          required: false
          description: Page sort, each item represents a sort column
        - in: query
          name: filter
          schema:
            type: string
            example: "bouwdro"
          required: false
          description: Search query, applied to all text fields.
        - in: query
          name: lessorId
          schema:
              type: integer
              format: int64
              example: '1'
          required: false
      responses:
        200:
          description: Successful result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRentalItemsResult'
    post:
      summary: Create a new rental item
      operationId: createRentalItem
      tags:
        - rentalItem
      security:
        - BearerAuth: [ ]
      parameters:
        - in: query
          name: lessorId
          schema:
            type: integer
            format: int64
            example: '1'
          required: true
          description: The id of the lessor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './utils/RentalItem.yaml#/components/schemas/RentalItemInput'
      responses:
        201:
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: './utils/RentalItem.yaml#/components/schemas/RentalItem'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RentalItemImagesResult:
      type: object
      properties:
        _embedded:
          type: array
          items:
            $ref: './utils/RentalItem.yaml#/components/schemas/Image'
    GetRentalItemsResult:
      type: object
      required:
        - _embedded
        - page
      properties:
        _embedded:
          type: array
          items:
            $ref: './utils/RentalItem.yaml#/components/schemas/RentalItem'
        page:
          $ref: './utils/PaginationResponse.yaml'
