openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /transaction/calculate-price:
    post:
      summary: Calculate the price for a transaction
      operationId: calculatePrice
      tags:
        - transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionCalculationInput'
      responses:
        200:
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionCalculationResult'
components:
  schemas:
    TransactionCalculationInput:
      type: object
      required:
        - startDate
        - endDate
        - rentalItemId
      properties:
        startDate:
          type: string
          format: date
          description: The start date
        endDate:
          type: string
          format: date
          description: The end date
        rentalItemId:
          type: integer
          format: int64
    TransactionCalculationResult:
      type: object
      required:
        - price
      properties:
        price:
          type: number
