openapi: 3.0.3
info:
  title: ShareRental - OpenAPI 3.0
  version: 0.0.1
paths:
  /transaction/mollie-callback:
    post:
      summary: callback for mollie payment
      description: https://docs.mollie.com/overview/webhooks
      tags:
        - transaction
      operationId: mollieCallback
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: The unique identifier for the payment transaction.
              required:
                - id
      responses:
        200:
          description: Webhook successfully processed.
  /transaction:
    post:
      summary: Create a transaction between a lessor and renter
      operationId: startTransaction
      tags:
        - transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionRequest'
      responses:
        200:
          description: Successfully created transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactionResponse'
  /transaction/calculate-price:
    post:
      summary: Calculate the price for a transaction
      operationId: calculatePrice
      tags:
        - transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionCalculationInput'
      responses:
        200:
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionCalculationResult'
  /transaction/get-amount-available-for-date:
    post:
      summary: Get the available amount of items for a specific date range.
      operationId: getAmountAvailableForDate
      tags:
        - transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAmountAvailableRequest'
      responses:
        200:
          description: The amount of items available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAmountAvailableResponse'
components:
  schemas:
    GetAmountAvailableResponse:
      type: object
      required:
        - amountAvailable
      properties:
        amountAvailable:
          type: integer
    GetAmountAvailableRequest:
      type: object
      required:
        - startDate
        - endDate
        - rentalItemId
      properties:
        startDate:
          type: string
          format: date
          description: The start date
        endDate:
          type: string
          format: date
          description: The end date
        rentalItemId:
          type: integer
          format: int64
    TransactionCalculationInput:
      type: object
      required:
        - startDate
        - endDate
        - rentalItemId
        - amount
      properties:
        startDate:
          type: string
          format: date
          description: The start date
        endDate:
          type: string
          format: date
          description: The end date
        rentalItemId:
          type: integer
          format: int64
        amount:
          type: integer
    TransactionCalculationResult:
      type: object
      required:
        - price
      properties:
        price:
          type: number
    CreateTransactionRequest:
      type: object
      required:
        - rentalItemId
        - startDate
        - endDate
        - amount
      properties:
        startDate:
          type: string
          format: date
          description: The start date
        endDate:
          type: string
          format: date
          description: The end date
        rentalItemId:
          type: integer
          format: int64
        amount:
          type: integer
          minimum: 1
    CreateTransactionResponse:
      type: object
      properties:
        redirectUrl:
          type: string
          description: Mollie hosted checkout url
