name: CI for API, and deploy to Cloud run

on:
  push:
    branches: [ master ]

jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: bootBuildImage

      - name: Configure GCP credentials
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          workload_identity_provider: 'projects/483629016643/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-workload-provider'
          service_account: 'github-action@sharerental-b66f7.iam.gserviceaccount.com'
          access_token_lifetime: 300s

      - name: Log in to the Artifact registry
        uses: docker/login-action@v1
        with:
          registry: europe-west4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push Docker images
        run: |
          # Build a docker container and push it to ECR
          docker push <imgNameHere>